project:
  type: website

website:
  title: "Davis Vaughan"
  navbar:
    right:
      - text: "Posts"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/DavisVaughan
format:
  html:
    theme:
      - litera
      - custom.scss
    css: styles.css

editor: visual
